package org.dynamisfx.simulation.coupling;

/**
 * Reason emitted by coupling policy evaluation.
 */
public enum CouplingDecisionReason {
    NO_CHANGE,
    PROMOTE_DISTANCE_THRESHOLD,
    PROMOTE_ALTITUDE_THRESHOLD,
    PROMOTE_PREDICTED_INTERCEPT,
    DEMOTE_DISTANCE_THRESHOLD,
    DEMOTE_ALTITUDE_THRESHOLD,
    DEMOTE_PREDICTED_EXIT,
    BLOCKED_BY_CONTACT,
    BLOCKED_BY_COOLDOWN,
    MISSING_DISTANCE_OBSERVATION,
    UNSUPPORTED_MODE
}
